// src/lib/pdf/brand.js
// ops-1-pdf-brand
//
// Reusable PDF branding for ALL Klassrun document exports (report cards now;
// exam/note/scheme export reuses this next). Renders a branded header band
// with the school logo (best-effort fetch from Cloudinary) + school name,
// and exposes the palette + a footer. Pure pdfkit; no headless browser.

const BRAND = Object.freeze({
  green: '#33aa42',
  navy: '#131b26',
  grey: '#6b7280',
  hair: '#e5e7eb',
});

// Fetch a remote image (e.g. Cloudinary logo) as a Buffer. Best-effort:
// returns null on any failure so a missing/broken logo never breaks a PDF.
async function fetchImageBuffer(url) {
  if (!url || typeof url !== 'string') return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const ab = await res.arrayBuffer();
    return Buffer.from(ab);
  } catch (_e) {
    return null;
  }
}

// Draw the branded header. Returns the y-coordinate to continue drawing below.
// `logoBuffer` is optional and pre-fetched by the caller (keeps this sync-safe).
function drawHeader(doc, { schoolName, title, subtitle, logoBuffer }) {
  const left = doc.page.margins.left;
  const top = doc.page.margins.top;
  const right = doc.page.width - doc.page.margins.right;

  let textX = left;
  if (logoBuffer) {
    try {
      doc.image(logoBuffer, left, top, { fit: [48, 48] });
      textX = left + 60;
    } catch (_e) {
      textX = left;
    }
  }

  doc
    .fillColor(BRAND.navy)
    .font('Helvetica-Bold')
    .fontSize(16)
    .text(schoolName || 'School', textX, top, { width: right - textX });

  if (title) {
    doc
      .fillColor(BRAND.green)
      .font('Helvetica-Bold')
      .fontSize(12)
      .text(title, textX, doc.y + 2, { width: right - textX });
  }

  if (subtitle) {
    doc
      .fillColor(BRAND.grey)
      .font('Helvetica')
      .fontSize(9)
      .text(subtitle, textX, doc.y + 1, { width: right - textX });
  }

  const lineY = Math.max(doc.y, top + 52) + 6;
  doc
    .moveTo(left, lineY)
    .lineTo(right, lineY)
    .lineWidth(1)
    .strokeColor(BRAND.green)
    .stroke();

  doc.fillColor('black').font('Helvetica').fontSize(10);
  doc.y = lineY + 10;
  return doc.y;
}

function drawFooter(doc, text) {
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const y = doc.page.height - doc.page.margins.bottom + 8;
  doc
    .fillColor(BRAND.grey)
    .font('Helvetica')
    .fontSize(8)
    .text(text || 'Generated by Klassrun', left, y, {
      width: right - left,
      align: 'center',
      lineBreak: false,
    });
  doc.fillColor('black');
}

module.exports = { BRAND, fetchImageBuffer, drawHeader, drawFooter };
