-- Hotfix Batch 2C Phase 3b: Subject.teacher relation declaration.
--
-- This migration intentionally contains NO SQL. The change is Prisma
-- relation metadata only (the FK column "teacherId" was added in Phase 3b
-- and exists in the database; this hotfix only adds the schema-side
-- relation declaration so the generated Prisma client exposes a `teacher`
-- field on Subject).
--
-- Prisma still requires a migration file when the schema changes, even
-- when no DDL runs. This file's purpose is to keep _prisma_migrations
-- in sync between local and Neon.

-- (intentionally empty)
